# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/henry/Projects/textgrab/textgrab/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setObjectName("central_widget")
        MainWindow.setCentralWidget(self.central_widget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_grab_from_clipboard = QtWidgets.QAction(MainWindow)
        self.action_grab_from_clipboard.setObjectName("action_grab_from_clipboard")
        self.action_screenshot = QtWidgets.QAction(MainWindow)
        self.action_screenshot.setObjectName("action_screenshot")
        self.toolBar.addAction(self.action_grab_from_clipboard)
        self.toolBar.addAction(self.action_screenshot)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_grab_from_clipboard.setText(_translate("MainWindow", "Grab From Clipboard"))
        self.action_screenshot.setText(_translate("MainWindow", "Screenshot"))
